apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: wildflyappservers.wildfly.banzaicloud.com
spec:
  group: wildfly.banzaicloud.com
  names:
    kind: WildflyAppServer
    listKind: WildflyAppServerList
    plural: wildflyappservers
    singular: wildflyappserver
  scope: Namespaced
  version: v1alpha1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wildfly-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: wildfly-operator
  template:
    metadata:
      labels:
        name: wildfly-operator
    spec:
      containers:
        - name: wildfly-operator
          image: banzaicloud/wildfly-operator:0.0.5
          command:
          - wildfly-operator
          imagePullPolicy: IfNotPresent
